version: "3.7"
services:
  app:
    build:
      args:
        user: dsum
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    environment:
      DB_HOST: db:3306
    volumes:
      - ./app:/var/www
    networks:
      - dsum

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dsum

  nginx:
    image: nginx:1.16-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - dsum

volumes:
  db_data:

networks:
  dsum:
    driver: bridge
